    <div id="menu">
        <a href="index.php">Inicio</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
        <a href="FormPersonasINS.php">Insertar</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
        <a href="FormPersonasDEL.php">Eliminar</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
        <a href="FormPersonasUPD.php">Actualizar</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;                
        <a href="FormPersonasVER.php">Visualizar</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
        <a href="Logout.php">Salir</a>                        
    </div>