    <div id="menu">
    
        <a href="index.php">Inicio</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
    <div class= "menuu">
        
        <ul>Títulos&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp; 
    
    
                                <li><a href="FormProyectoINS.php">Insertar</a></li> 
                                <li><a href="FormPersonasDEL.php">Eliminar</a></li>
                                <li><a href="FormPersonasUPD.php">Actualizar</a></li>
        </ul>                        
    
        
        <ul>Género&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
        
                                <li><a href="FormProyectoINS.php">Insertar</a></li> 
                                <li><a href="FormPersonasUPD.php">Actualizar</a></li>
        </ul> 
        
        </div>                       
      <a href="Logout.php">Salir</a>
        
                            
  
    </div>